[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
optimizer = true
optimizer_runs = 10000
gas_reports = ["*"]

[profile.gas]
test = 'test_gas'

[fuzz]
runs = 2500
max_test_rejects = 0
